import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import localFont from "next/font/local";
import Navbar from './components/Navbar';
//import $ from "jquery";
//import './js/owl-carousel'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Navbar />
        {children}
      </body>
    </html>
  );
}
